# Generated by Django 5.2.7 on 2025-10-25 14:32

import day_wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='db_password',
            field=models.CharField(default=day_wallet.models.generate_db_password, max_length=255, verbose_name='Пароль для CouchDB'),
        ),
    ]
