# Generated by Django 5.2.7 on 2025-11-17 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_wallet', '0002_appuser_db_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('superuser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
            },
        ),
    ]
